import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {createSections} from './sections.mjs';
import {createArchive} from './archive.mjs';
import vm from 'node:vm';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const revision=file=>createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex').slice(0,10);
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data/catalog.js'),'utf8'),sandbox);
const works=sandbox.window.ANA_CATALOG;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={arrow:'M4 12h15M13 5l7 7-7 7',back:'M20 12H5m6-7-7 7 7 7',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M18 6 6 18',menu:'M3 6h18M3 12h18M3 18h18',down:'M12 3v17m-7-7 7 7 7-7',instagram:'M7 3h10a4 4 0 0 1 4 4v10a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V7a4 4 0 0 1 4-4zm9 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0zm1-6h.01',whatsapp:'M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 21l1.7-5a8.5 8.5 0 1 1 15.8-4.4ZM8 7.5c.4 4 2.6 6.2 6.5 7l1-2-2-1-1 1c-1.3-.7-2.3-1.7-3-3l1-1-1-2Z',share:'M16 6 8 11m8 7-8-5M21 5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0ZM8 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm13 7a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Z',pin:'M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 0 1 14 0Zm-4 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',mail:'M3 5h18v14H3Zm0 1 9 7 9-7',check:'m5 12 4 4L20 5'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.arrow}"/></svg>`;
const wa='https://wa.me/5511919007582';
const marked=t=>t.replace(/\.$/,'<span class="pink">.</span>');
const wordmark=(b='')=>`<span class="wordmark" aria-hidden="true"><img src="${b}assets/ui/ana-byte-mark.png" alt="" width="112" height="111"></span>`;
const eyebrow=(num,label)=>`<p class="eyebrow"><span>${num}</span><i aria-hidden="true"></i>${label}</p>`;
const img=(w,b='',classes='',eager=false)=>`<img class="${classes}" src="${b+esc(w.src)}" alt="${esc(w.alt)}" width="${w.width||900}" height="${w.height||1200}" loading="${eager?'eager':'lazy'}" decoding="async" style="--crop-desktop:${esc(w.desktopPosition||'50% 50%')};--crop-mobile:${esc(w.mobilePosition||'50% 50%')}">`;
function artButton(w,b,classes='',i=0){return `<a class="art-card ${classes}" href="${b+esc(w.src)}" data-art="${esc(w.id)}" aria-label="Explorar ${esc(w.title)}">${img(w,b)}<span class="card-caption"><small>${String(i+1).padStart(2,'0')}</small><strong>${esc(w.title)}</strong></span><span class="art-plus" aria-hidden="true">${icon('plus')}</span></a>`}
function nav(b,page){return `<a class="skip-link" href="#conteudo">Ir para o conteúdo</a><header class="rail"><a class="brand" href="${b}index.html" aria-label="Ana Byte, início">${wordmark(b)}<small>TATTOO ARTIST</small></a>${page==='inicio'?'<span class="rail-location">Studio em São Paulo</span>':''}<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="Abrir navegação">${icon('menu')}</button><nav id="main-nav" aria-label="Navegação principal">${[['01','Início','inicio',`${b}index.html`],['02','Trabalhos','trabalhos',page==='inicio'?'#trabalhos':`${b}index.html#trabalhos`],['03','Processo','processo',`${b}index.html#processo`],['04','Sobre','sobre','#sobre'],['05','Contato','contato',`${b}index.html#contato`]].map(([n,t,id,url])=>`<a href="${url}" data-nav="${id}" ${page===id?'aria-current="page"':''}><span>${n}</span>${t}</a>`).join('')}<button class="menu-effects" aria-pressed="false">Pausar efeitos</button></nav><div class="rail-bottom"><span class="rail-jp" lang="ja" aria-hidden="true">アナ</span><a href="https://www.instagram.com/ana.byte/" target="_blank" rel="noopener" aria-label="Instagram da Ana Byte">${icon('instagram')}</a><a href="mailto:anabitencourttattoos@gmail.com" aria-label="E-mail da Ana Byte">${icon('mail')}</a><small>SÃO PAULO<br>BRASIL</small></div></header><div class="reading-progress" role="progressbar" aria-label="Progresso de leitura da página" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span class="reading-progress-fill"></span></div>`}
const floating=()=>`<a class="floating-whatsapp" href="${wa}" target="_blank" rel="noopener" aria-label="Falar com Ana no WhatsApp">${icon('whatsapp')}<span>Vamos conversar</span></a>`;
const footer=(b='')=>`<footer class="footer"><a class="footer-brand" href="${b}index.html" aria-label="Ana Byte, início">${wordmark(b)}<small>TATUAGEM & ARTE DIGITAL</small></a><a href="https://www.instagram.com/ana.byte/" target="_blank" rel="noopener">@ana.byte ${icon('instagram')}</a><small>São Paulo, Brasil<br>Atendimento com hora marcada</small><button class="motion-switch" type="button" aria-pressed="false">Pausar efeitos</button><a href="#conteudo" aria-label="Voltar ao início da página">${icon('down','up')}</a></footer>`;
const dialog=()=>`<dialog class="art-dialog" aria-labelledby="detail-title"><div class="dialog-bar"><span class="eyebrow">ARQUIVO VIVO <span data-detail-counter></span></span><button class="icon-button dialog-close" aria-label="Fechar obra">${icon('close')}</button></div><div class="dialog-grid"><div class="dialog-picture"><img data-detail-image alt=""><button class="icon-button detail-prev" aria-label="Obra anterior">${icon('back')}</button><button class="icon-button detail-next" aria-label="Próxima obra">${icon('arrow')}</button></div><div class="detail-copy"><p class="eyebrow" data-detail-kind></p><h2 id="detail-title" data-detail-title></h2><p data-detail-description></p><div class="detail-notes"><div><span class="annotation-line"></span><h3>O traço</h3><p data-detail-technique></p></div><div><span class="annotation-line"></span><h3>O encontro</h3><p data-detail-difference></p></div></div><a class="neon-button" data-detail-contact target="_blank" rel="noopener">Quero criar algo nessa direção ${icon('arrow')}</a><button class="text-link share-work">Compartilhar obra ${icon('share')}</button><span class="share-status" role="status"></span></div></div></dialog>`;
function head(title,desc,b,page){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#080A0F"><title>${title}</title><meta name="description" content="${desc}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><meta property="og:image" content="${b}assets/artist/15-ana-working.jpg"><link rel="icon" href="${b}assets/ui/favicon.svg" type="image/svg+xml"><link rel="preload" href="${b}assets/fonts/Orbitron-Variable.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${b}assets/fidelity.css?v=${revision('assets/fidelity.css')}"><noscript><style>.menu-toggle,.menu-effects,.motion-switch,.archive-replay,.ambience-toggle,.filters,.sort-label{display:none!important}.portfolio-grid .art-card{display:block!important}.portfolio-browser{display:flex!important;flex-direction:column!important}.portfolio-layout{display:contents!important}.selected-work{display:block!important;order:-1;position:static!important;max-width:500px;margin:0 auto 24px}.selected-art-copy{display:none!important}.portfolio-layout{grid-template-columns:1fr!important}@media(max-width:1023px){.rail nav{display:flex!important;position:static!important;flex-wrap:wrap!important;flex-direction:row!important;gap:0!important;padding:5px!important}.rail{position:relative!important;inset:auto!important;height:auto!important;display:flex!important;flex-wrap:wrap!important;background:#050a11!important;padding:12px 23px!important}.rail nav a{font-size:10px!important;padding:8px!important}.rail nav a span{display:none!important}.rail .brand{flex-direction:row!important}.rail .wordmark{width:59px!important;height:59px!important}.hero,.portfolio-hero,.artist-full{margin-top:0!important}}</style></noscript><script defer src="${b}data/catalog.js"></script><script defer src="${b}assets/vendor/gsap.min.js"></script><script defer src="${b}assets/vendor/ScrollTrigger.min.js"></script><script defer src="${b}assets/v3.js?v=${revision('assets/v3.js')}"></script><script type="application/ld+json">{"@context":"https://schema.org","@type":"Person","name":"Ana Byte","jobTitle":"Tatuadora e artista visual","sameAs":["https://www.instagram.com/ana.byte/"],"address":{"@type":"PostalAddress","addressLocality":"São Paulo","addressCountry":"BR"}}</script></head><body data-page="${page}" data-base="${b}">${nav(b,page)}`}
const gallery=createArchive({works,img,icon,artButton,esc,wa});
const {hero,archive,process,artist,contact}=createSections({works,img,icon,eyebrow,artButton,wa,gallery});
for(const [file,page,b,title,desc,content] of [
 ['index.html','inicio','','Ana Byte | Um lugar entre mundos','Tatuagem autoral e arte digital em São Paulo. Conheça o universo de Ana Byte, explore trabalhos reais e conte sua ideia.',()=>hero()+archive()+process()+artist()+contact()]
]){fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),head(title,desc,b,page)+`<main id="conteudo">${content()}${footer(b)}</main>${floating()}${dialog()}<div class="menu-scrim" hidden></div></body></html>`)}
fs.mkdirSync(path.join(root,'sobre'),{recursive:true});
fs.writeFileSync(path.join(root,'sobre/index.html'),`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sobre Ana Byte</title><link rel="canonical" href="../index.html#sobre"><script>location.replace(new URL('../index.html#sobre',location.href))</script><style>body{background:#05070b;color:#e8f1f4;font:18px/1.7 system-ui;padding:10vh 8vw}a{color:#62e5ed}</style></head><body><h1>Sobre Ana Byte</h1><p>A história da Ana faz parte da página principal.</p><a href="../index.html#sobre">Conhecer a Ana</a></body></html>`);
fs.mkdirSync(path.join(root,'portfolio'),{recursive:true});
fs.writeFileSync(path.join(root,'portfolio/index.html'),`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Arquivo Vivo | Ana Byte</title><link rel="canonical" href="../index.html#trabalhos"><script>const destination=new URL('../index.html',location.href);destination.search=location.search;destination.hash=location.hash||'trabalhos';location.replace(destination.href);</script><style>body{background:#05070b;color:#e8f1f4;font:18px/1.7 system-ui;padding:10vh 8vw}a{color:#62e5ed}</style></head><body><h1>Arquivo Vivo</h1><p>O acervo faz parte da experiência principal.</p><a href="../index.html#trabalhos">Explorar os trabalhos da Ana</a></body></html>`);
console.log('V3 construída: início com Arquivo Vivo, sobre e redirecionamento do acervo. '+works.length+' obras reais.');
