const { chromium } = require('C:/Users/crist.PC/AppData/Local/npm-cache/_npx/e41f203b7505f1fb/node_modules/playwright-core');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
 const out = path.join(__dirname, 'cinema'); fs.mkdirSync(out, { recursive: true });
 const browser = await chromium.launch({ headless: true });
 const page = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 const shot = name => page.screenshot({ path: path.join(out, name + '.png') });
 const ready = name => page.waitForFunction(name => window.AnaFlight.scene === name && !window.AnaFlight.travelling, name);
 await page.goto('http://127.0.0.1:4178/', { waitUntil: 'domcontentloaded' });
 await page.locator('.byte-entry__start:not([disabled])').waitFor();
 await page.waitForTimeout(1200); await page.keyboard.press('Escape');
 assert.equal(await page.locator('.byte-entry').count(), 1);
 await shot('01-loading');
 await page.locator('.byte-entry__start').click();
 await page.locator('.byte-entry').waitFor({ state: 'detached' });
 await shot('02-city');
 assert.equal(await page.locator('#obras').evaluate(e => e.inert), true);
 await page.locator('.discover-world').click();
 await page.waitForFunction(() => document.querySelector('#city-flight').currentTime > .8);
 assert.equal(await page.evaluate(() => window.AnaFlight.travelling), true);
 await shot('03-video');
 await ready('works'); await page.waitForTimeout(250); await shot('04-works');
 console.log('VIDEO_TO_WORKS', await page.locator('#city-flight').evaluate(v => ({ time: v.currentTime, duration: v.duration, loop: v.loop })));
 await page.locator('#next-work').click(); await page.waitForTimeout(200);
 assert.match(await page.locator('#work-counter').textContent(), /02/);
 await page.locator('#open-collection').click();
 assert.equal(await page.locator('#collection-grid button').count(), 15);
 await page.locator('#collection-grid button').nth(4).click();
 await page.locator('#art-dialog[open]').waitFor();
 await page.locator('#close-art').click();
 await page.waitForFunction(() => document.body.style.overflow === '');
 assert.equal(await page.evaluate(() => document.body.style.overflow), '');
 await page.locator('.gallery-facade [data-destination=artist]').click();
 await page.waitForTimeout(400); await page.locator('.skip-flight').click();
 await ready('artist'); await page.waitForTimeout(250); await shot('05-artist');
 await page.locator('.artist-actions a').first().click();
 await page.locator('.ana-interior-layer.is-open iframe').waitFor();
 await page.waitForTimeout(1000); await shot('06-interior');
 await page.locator('.ana-interior-layer__close').click();
 await page.waitForTimeout(800);
 assert.equal(await page.evaluate(() => window.AnaFlight.scene), 'artist');
 await page.locator('.journey-nav [data-destination=contact]').click();
 await page.locator('.skip-flight').click(); await ready('contact'); await shot('07-contact');
 await page.setViewportSize({ width: 360, height: 640 });
 await page.locator('.journey-nav [data-destination=works]').click();
 await page.locator('.skip-flight').click(); await ready('works'); await shot('08-works-small');
 await page.locator('.journey-nav [data-destination=artist]').click();
 await page.locator('.skip-flight').click(); await ready('artist'); await shot('09-artist-small');
 console.log('SMALL', await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth, controls: [...document.querySelectorAll('.is-current button, .is-current a')].map(e => {const r=e.getBoundingClientRect();return {text:e.textContent.trim(),x:r.x,y:r.y,w:r.width,h:r.height}}) })));
 await page.setViewportSize({ width: 1440, height: 900 }); await page.waitForTimeout(350);
 await shot('10-artist-desktop');
 const still = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
 await still.goto('http://127.0.0.1:4178/?scene=works');
 await still.locator('.byte-entry__start:not([disabled])').click();
 await still.locator('.byte-entry').waitFor({ state: 'detached' });
 await still.locator('.journey-nav [data-destination=artist]').click();
 assert.equal(await still.evaluate(() => window.AnaFlight.scene), 'artist');
 assert.equal(await still.locator('#city-flight').evaluate(v => v.currentTime), 0);
 const plain = await browser.newPage({ javaScriptEnabled: false, viewport: { width:390, height:844 } });
 await plain.goto('http://127.0.0.1:4178/');
 assert.equal(await plain.locator('[data-work]').count(), 15);
 assert.equal(await plain.locator('.static-collection').isVisible(), true);
 console.log('ERRORS', errors); assert.deepEqual(errors, []);
 await browser.close();
})().catch(e => { console.error(e); process.exit(1); });
